-- Add Audit Columns to All Tables
-- Execute this script against your PIC_Certificates_Angular database

-- Users table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'CreatedBy')
  ALTER TABLE Users ADD CreatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'UpdatedBy')
  ALTER TABLE Users ADD UpdatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'DeletedBy')
  ALTER TABLE Users ADD DeletedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'IsDeleted')
  ALTER TABLE Users ADD IsDeleted BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'DeletedDate')
  ALTER TABLE Users ADD DeletedDate DATETIME2 NULL;

-- CompanyDetails table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CompanyDetails' AND COLUMN_NAME = 'CreatedBy')
  ALTER TABLE CompanyDetails ADD CreatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CompanyDetails' AND COLUMN_NAME = 'UpdatedBy')
  ALTER TABLE CompanyDetails ADD UpdatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CompanyDetails' AND COLUMN_NAME = 'DeletedBy')
  ALTER TABLE CompanyDetails ADD DeletedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CompanyDetails' AND COLUMN_NAME = 'IsDeleted')
  ALTER TABLE CompanyDetails ADD IsDeleted BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CompanyDetails' AND COLUMN_NAME = 'DeletedDate')
  ALTER TABLE CompanyDetails ADD DeletedDate DATETIME2 NULL;

-- Certificates table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Certificates' AND COLUMN_NAME = 'CreatedBy')
  ALTER TABLE Certificates ADD CreatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Certificates' AND COLUMN_NAME = 'UpdatedBy')
  ALTER TABLE Certificates ADD UpdatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Certificates' AND COLUMN_NAME = 'DeletedBy')
  ALTER TABLE Certificates ADD DeletedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Certificates' AND COLUMN_NAME = 'IsDeleted')
  ALTER TABLE Certificates ADD IsDeleted BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Certificates' AND COLUMN_NAME = 'DeletedDate')
  ALTER TABLE Certificates ADD DeletedDate DATETIME2 NULL;

-- Equipment table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Equipment' AND COLUMN_NAME = 'CreatedBy')
  ALTER TABLE Equipment ADD CreatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Equipment' AND COLUMN_NAME = 'UpdatedBy')
  ALTER TABLE Equipment ADD UpdatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Equipment' AND COLUMN_NAME = 'DeletedBy')
  ALTER TABLE Equipment ADD DeletedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Equipment' AND COLUMN_NAME = 'IsDeleted')
  ALTER TABLE Equipment ADD IsDeleted BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Equipment' AND COLUMN_NAME = 'DeletedDate')
  ALTER TABLE Equipment ADD DeletedDate DATETIME2 NULL;

-- Locations table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Locations' AND COLUMN_NAME = 'CreatedBy')
  ALTER TABLE Locations ADD CreatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Locations' AND COLUMN_NAME = 'UpdatedBy')
  ALTER TABLE Locations ADD UpdatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Locations' AND COLUMN_NAME = 'DeletedBy')
  ALTER TABLE Locations ADD DeletedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Locations' AND COLUMN_NAME = 'IsDeleted')
  ALTER TABLE Locations ADD IsDeleted BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Locations' AND COLUMN_NAME = 'DeletedDate')
  ALTER TABLE Locations ADD DeletedDate DATETIME2 NULL;

-- Roles table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Roles' AND COLUMN_NAME = 'CreatedBy')
  ALTER TABLE Roles ADD CreatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Roles' AND COLUMN_NAME = 'UpdatedBy')
  ALTER TABLE Roles ADD UpdatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Roles' AND COLUMN_NAME = 'DeletedBy')
  ALTER TABLE Roles ADD DeletedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Roles' AND COLUMN_NAME = 'IsDeleted')
  ALTER TABLE Roles ADD IsDeleted BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Roles' AND COLUMN_NAME = 'DeletedDate')
  ALTER TABLE Roles ADD DeletedDate DATETIME2 NULL;

-- UserRoleMappings table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UserRoleMappings' AND COLUMN_NAME = 'CreatedBy')
  ALTER TABLE UserRoleMappings ADD CreatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UserRoleMappings' AND COLUMN_NAME = 'UpdatedBy')
  ALTER TABLE UserRoleMappings ADD UpdatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UserRoleMappings' AND COLUMN_NAME = 'DeletedBy')
  ALTER TABLE UserRoleMappings ADD DeletedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UserRoleMappings' AND COLUMN_NAME = 'IsDeleted')
  ALTER TABLE UserRoleMappings ADD IsDeleted BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UserRoleMappings' AND COLUMN_NAME = 'DeletedDate')
  ALTER TABLE UserRoleMappings ADD DeletedDate DATETIME2 NULL;

-- Applications table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Applications' AND COLUMN_NAME = 'CreatedBy')
  ALTER TABLE Applications ADD CreatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Applications' AND COLUMN_NAME = 'UpdatedBy')
  ALTER TABLE Applications ADD UpdatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Applications' AND COLUMN_NAME = 'DeletedBy')
  ALTER TABLE Applications ADD DeletedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Applications' AND COLUMN_NAME = 'IsDeleted')
  ALTER TABLE Applications ADD IsDeleted BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Applications' AND COLUMN_NAME = 'DeletedDate')
  ALTER TABLE Applications ADD DeletedDate DATETIME2 NULL;

-- RoleAndApplicationWisePermissions table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RoleAndApplicationWisePermissions' AND COLUMN_NAME = 'CreatedBy')
  ALTER TABLE RoleAndApplicationWisePermissions ADD CreatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RoleAndApplicationWisePermissions' AND COLUMN_NAME = 'UpdatedBy')
  ALTER TABLE RoleAndApplicationWisePermissions ADD UpdatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RoleAndApplicationWisePermissions' AND COLUMN_NAME = 'DeletedBy')
  ALTER TABLE RoleAndApplicationWisePermissions ADD DeletedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RoleAndApplicationWisePermissions' AND COLUMN_NAME = 'IsDeleted')
  ALTER TABLE RoleAndApplicationWisePermissions ADD IsDeleted BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RoleAndApplicationWisePermissions' AND COLUMN_NAME = 'DeletedDate')
  ALTER TABLE RoleAndApplicationWisePermissions ADD DeletedDate DATETIME2 NULL;

-- AuditLogs table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AuditLogs' AND COLUMN_NAME = 'CreatedBy')
  ALTER TABLE AuditLogs ADD CreatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AuditLogs' AND COLUMN_NAME = 'UpdatedBy')
  ALTER TABLE AuditLogs ADD UpdatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AuditLogs' AND COLUMN_NAME = 'DeletedBy')
  ALTER TABLE AuditLogs ADD DeletedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AuditLogs' AND COLUMN_NAME = 'IsDeleted')
  ALTER TABLE AuditLogs ADD IsDeleted BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AuditLogs' AND COLUMN_NAME = 'DeletedDate')
  ALTER TABLE AuditLogs ADD DeletedDate DATETIME2 NULL;

-- LetterHeads table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LetterHeads' AND COLUMN_NAME = 'CreatedBy')
  ALTER TABLE LetterHeads ADD CreatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LetterHeads' AND COLUMN_NAME = 'UpdatedBy')
  ALTER TABLE LetterHeads ADD UpdatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LetterHeads' AND COLUMN_NAME = 'DeletedBy')
  ALTER TABLE LetterHeads ADD DeletedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LetterHeads' AND COLUMN_NAME = 'IsDeleted')
  ALTER TABLE LetterHeads ADD IsDeleted BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LetterHeads' AND COLUMN_NAME = 'DeletedDate')
  ALTER TABLE LetterHeads ADD DeletedDate DATETIME2 NULL;

-- EmailDomains table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EmailDomains' AND COLUMN_NAME = 'CreatedBy')
  ALTER TABLE EmailDomains ADD CreatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EmailDomains' AND COLUMN_NAME = 'UpdatedBy')
  ALTER TABLE EmailDomains ADD UpdatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EmailDomains' AND COLUMN_NAME = 'DeletedBy')
  ALTER TABLE EmailDomains ADD DeletedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EmailDomains' AND COLUMN_NAME = 'IsDeleted')
  ALTER TABLE EmailDomains ADD IsDeleted BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EmailDomains' AND COLUMN_NAME = 'DeletedDate')
  ALTER TABLE EmailDomains ADD DeletedDate DATETIME2 NULL;

-- EmailAccounts table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EmailAccounts' AND COLUMN_NAME = 'CreatedBy')
  ALTER TABLE EmailAccounts ADD CreatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EmailAccounts' AND COLUMN_NAME = 'UpdatedBy')
  ALTER TABLE EmailAccounts ADD UpdatedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EmailAccounts' AND COLUMN_NAME = 'DeletedBy')
  ALTER TABLE EmailAccounts ADD DeletedBy INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EmailAccounts' AND COLUMN_NAME = 'IsDeleted')
  ALTER TABLE EmailAccounts ADD IsDeleted BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EmailAccounts' AND COLUMN_NAME = 'DeletedDate')
  ALTER TABLE EmailAccounts ADD DeletedDate DATETIME2 NULL;

PRINT 'Audit columns added successfully to all tables';
