-- Simple SQL Script to Check Current Audit Fields in Your Database
-- This version is simpler and more compatible

PRINT '=== CHECKING CURRENT AUDIT FIELDS ===';
PRINT '';

-- Check for basic audit fields (CreatedDate, UpdatedDate, DeletedDate)
SELECT 
    'Basic Audit Fields (CreatedDate, UpdatedDate, DeletedDate)' as 'Field Type',
    TABLE_NAME as 'Table',
    COLUMN_NAME as 'Field',
    DATA_TYPE as 'Type',
    IS_NULLABLE as 'Nullable'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE COLUMN_NAME IN ('CreatedDate', 'UpdatedDate', 'DeletedDate')
AND TABLE_SCHEMA = 'dbo'
ORDER BY TABLE_NAME, COLUMN_NAME;

PRINT '';
PRINT '=== CHECKING USER TRACKING FIELDS ===';
PRINT '';

-- Check for user tracking fields (CreatedBy, UpdatedBy, DeletedBy, IsDeleted)
SELECT 
    'User Tracking Fields (CreatedBy, UpdatedBy, DeletedBy, IsDeleted)' as 'Field Type',
    TABLE_NAME as 'Table',
    COLUMN_NAME as 'Field',
    DATA_TYPE as 'Type',
    IS_NULLABLE as 'Nullable'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE COLUMN_NAME IN ('CreatedBy', 'UpdatedBy', 'DeletedBy', 'IsDeleted')
AND TABLE_SCHEMA = 'dbo'
ORDER BY TABLE_NAME, COLUMN_NAME;

PRINT '';
PRINT '=== SUMMARY OF MISSING FIELDS ===';
PRINT '';

-- Simple check for missing fields in key tables
SELECT 
    'Users' as TableName,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'CreatedBy') THEN 'EXISTS' ELSE 'MISSING' END as CreatedBy,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'UpdatedBy') THEN 'EXISTS' ELSE 'MISSING' END as UpdatedBy,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'DeletedBy') THEN 'EXISTS' ELSE 'MISSING' END as DeletedBy,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'IsDeleted') THEN 'EXISTS' ELSE 'MISSING' END as IsDeleted;

SELECT 
    'CompanyDetails' as TableName,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CompanyDetails' AND COLUMN_NAME = 'CreatedBy') THEN 'EXISTS' ELSE 'MISSING' END as CreatedBy,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CompanyDetails' AND COLUMN_NAME = 'UpdatedBy') THEN 'EXISTS' ELSE 'MISSING' END as UpdatedBy,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CompanyDetails' AND COLUMN_NAME = 'DeletedBy') THEN 'EXISTS' ELSE 'MISSING' END as DeletedBy,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CompanyDetails' AND COLUMN_NAME = 'IsDeleted') THEN 'EXISTS' ELSE 'MISSING' END as IsDeleted;

SELECT 
    'Certificates' as TableName,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Certificates' AND COLUMN_NAME = 'CreatedBy') THEN 'EXISTS' ELSE 'MISSING' END as CreatedBy,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Certificates' AND COLUMN_NAME = 'UpdatedBy') THEN 'EXISTS' ELSE 'MISSING' END as UpdatedBy,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Certificates' AND COLUMN_NAME = 'DeletedBy') THEN 'EXISTS' ELSE 'MISSING' END as DeletedBy,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Certificates' AND COLUMN_NAME = 'IsDeleted') THEN 'EXISTS' ELSE 'MISSING' END as IsDeleted;

SELECT 
    'Equipment' as TableName,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Equipment' AND COLUMN_NAME = 'CreatedBy') THEN 'EXISTS' ELSE 'MISSING' END as CreatedBy,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Equipment' AND COLUMN_NAME = 'UpdatedBy') THEN 'EXISTS' ELSE 'MISSING' END as UpdatedBy,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Equipment' AND COLUMN_NAME = 'DeletedBy') THEN 'EXISTS' ELSE 'MISSING' END as DeletedBy,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Equipment' AND COLUMN_NAME = 'IsDeleted') THEN 'EXISTS' ELSE 'MISSING' END as IsDeleted;

SELECT 
    'Locations' as TableName,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Locations' AND COLUMN_NAME = 'CreatedBy') THEN 'EXISTS' ELSE 'MISSING' END as CreatedBy,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Locations' AND COLUMN_NAME = 'UpdatedBy') THEN 'EXISTS' ELSE 'MISSING' END as UpdatedBy,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Locations' AND COLUMN_NAME = 'DeletedBy') THEN 'EXISTS' ELSE 'MISSING' END as DeletedBy,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Locations' AND COLUMN_NAME = 'IsDeleted') THEN 'EXISTS' ELSE 'MISSING' END as IsDeleted;

PRINT '';
PRINT '=== INSTRUCTIONS ===';
PRINT '1. Run the add_missing_audit_fields.sql script to add the missing fields';
PRINT '2. After running the script, re-run this check to verify all fields are present';
PRINT '3. Your database will then have complete audit tracking capabilities';